### ISSUE TITLE
Do you use Loggin'JS? Come and say hi! 😃 

### ISSUE THREAD

**Issue by nombrekeff** [loggin-js/loggin-js#105]
Hi there, let's talk a bit!

I'm kinda curious to know if anybody is using this library, and what you think about it! If you use it or have used it, please consider leaving a comment!

😃

**Comment by dada513** [comment]
I've just started using it, looks great!

**Comment by nombrekeff** [comment]
That's awesome, please let me know if you need any help, find a bug 🐛  , or have some feature in mind 🚀
