### ISSUE TITLE
[docs] Improve/complete docs 

### ISSUE THREAD

**Issue by nombrekeff** [loggin-js/loggin-js#66]

**Comment by emm3ttarmstrong** [comment]
Hello, I'd like to add a few grammar improvements and spelling fixes to the readme.md file. I didn't touch the code, only the formatting! PR incoming.

**Comment by nombrekeff** [comment]
Hi there! I just merged it in. Thanks for the contribution, I really appreciate it!
Feel free to dig into the code if you feel like it!
